import numpy as np
from math import pi,sin,cos,log,sqrt
from random import random
from matplotlib import pyplot
from scipy import stats



def UniGaussianGen(m=0,s=1):
    #generated by Box-Muller
    #p value is a little high (~=0.5)
    return sqrt((-2)*log(random()))*cos(2*pi*random())*sqrt(s)+m

def PolyBasisGen(n,a,w):
    if(n!=len(w)):
        raise
    x=random()*20-10
    y=(sum(w[i]*(x**i) for i in range(n)))+UniGaussianGen(0,a)
    return (x,y)
